#!/usr/bin/env python3
"""
Test Bitwarden API Key Manager for OpenDiscourse MCP
This script tests the Bitwarden integration without database dependencies
"""

import os
import json
import subprocess
import sys
from pathlib import Path

# Bitwarden configuration
BITWARDEN_CONFIG = {
    "items": {
        "govinfo_api_key": {
            "name": "GovInfo API Key",
            "fields": ["api_key", "govinfo", "GovInfo"],
        },
        "congress_api_key": {
            "name": "Congress.gov API Key",
            "fields": ["api_key", "congress", "Congress.gov", "Congress"],
        },
    }
}


def check_bitwarden_cli():
    """Check if Bitwarden CLI is installed"""
    try:
        result = subprocess.run(["bw", "--version"], capture_output=True, text=True)
        print(f"✅ Bitwarden CLI found: {result.stdout.strip()}")
        return True
    except FileNotFoundError:
        print("❌ Bitwarden CLI not found")
        print("Please install Bitwarden CLI:")
        print("  npm install -g @bitwarden/cli")
        print("  or visit: https://bitwarden.com/help/article/cli/")
        return False


def test_unlock_bitwarden():
    """Test Bitwarden unlock functionality"""
    print("🔓 Testing Bitwarden unlock...")

    # Check status
    try:
        result = subprocess.run(["bw", "status"], capture_output=True, text=True)
        status = result.stdout.strip().lower()
        print(f"Current status: {status}")

        if "unlocked" in status:
            print("✅ Bitwarden is unlocked")
            return True
        elif "locked" in status:
            print("🔓 Bitwarden is locked - unlock required")
            print("To unlock:")
            print("  1. Set environment variables:")
            print("     export BITWARDEN_EMAIL='your-email@example.com'")
            print("     export BITWARDEN_PASSWORD='your-master-password'")
            print("  2. Or run: bw unlock")
            return False
        else:
            print(f"❓ Unknown status: {status}")
            return False
    except Exception as e:
        print(f"❌ Error checking status: {e}")
        return False


def test_api_key_search():
    """Test API key search functionality"""
    print("\n🔍 Testing API key search...")

    # Test search for GovInfo API Key
    try:
        result = subprocess.run(
            ["bw", "list", "items", "--search", "GovInfo"],
            capture_output=True,
            text=True,
        )

        if result.returncode == 0:
            items = json.loads(result.stdout)
            print(f"✅ Found {len(items)} items matching 'GovInfo'")

            for item in items:
                print(f"  📋 {item.get('name', 'Unknown')}")
                if item.get("id"):
                    print(f"     ID: {item['id']}")
        else:
            print("❌ No items found matching 'GovInfo'")
    except json.JSONDecodeError as e:
        print(f"❌ Error parsing search results: {e}")
    except Exception as e:
        print(f"❌ Error searching for items: {e}")


def test_env_file_update():
    """Test .env file update functionality"""
    print("\n📝 Testing .env file update...")

    env_file = Path(".env")
    test_keys = {
        "govinfo_api_key": "test_govinfo_key_12345",
        "congress_api_key": "test_congress_key_67890",
    }

    # Create test .env content
    env_content = [
        "# OpenDiscourse MCP Environment Variables\n",
        "# Generated by Bitwarden setup script\n",
        f"GOVINFO_API_KEY={test_keys['govinfo_api_key']}\n",
        f"CONGRESS_API_KEY={test_keys['congress_api_key']}\n",
        "# Database configuration\n",
        "DB_HOST=localhost\n",
        "DB_PORT=5432\n",
        "DB_NAME=opendiscourse\n",
        "DB_USER=opendiscourse\n",
        "DB_PASSWORD=opendiscourse123\n",
    ]

    try:
        with open(env_file, "w") as f:
            f.writelines(env_content)
        print(f"✅ Test .env file created at {env_file}")

        # Verify content
        with open(env_file, "r") as f:
            content = f.read()
            print("📄 .env file contents:")
            print(content)

        return True
    except Exception as e:
        print(f"❌ Failed to create .env file: {e}")
        return False


def test_database_config():
    """Test database configuration"""
    print("\n🗄️ Testing database configuration...")

    # Test if we can import psycopg2
    try:
        import psycopg2

        print("✅ psycopg2 module available")
    except ImportError:
        print("❌ psycopg2 module not available")
        print("Install with: pip install psycopg2-binary")
        return False

    # Test database connection string
    db_config = {
        "host": "localhost",
        "port": 5432,
        "database": "opendiscourse",
        "user": "opendiscourse",
        "password": "opendiscourse123",
    }

    print("📋 Database configuration:")
    for key, value in db_config.items():
        if key == "password":
            print(f"  {key}: {'*' * len(str(value))}")
        else:
            print(f"  {key}: {value}")

    # Test connection (without actually connecting)
    conn_string = f"postgresql://{db_config['user']}:{db_config['password']}@{db_config['host']}:{db_config['port']}/{db_config['database']}"
    print(
        f"\n🔗 Connection string: postgresql://{db_config['user']}:***@{db_config['host']}:{db_config['port']}/{db_config['database']}"
    )

    return True


def main():
    """Main test function"""
    print("🧪 OpenDiscourse MCP - Bitwarden Integration Test")
    print("=" * 50)

    # Test 1: Bitwarden CLI
    if not check_bitwarden_cli():
        print("\n❌ Please install Bitwarden CLI first")
        sys.exit(1)

    # Test 2: Bitwarden unlock
    if not test_unlock_bitwarden():
        print("\n❌ Please unlock Bitwarden first")
        sys.exit(1)

    # Test 3: API key search
    test_api_key_search()

    # Test 4: .env file update
    test_env_file_update()

    # Test 5: Database configuration
    test_database_config()

    print("\n✅ All tests completed!")
    print("\n📋 Next Steps:")
    print("1. Add API keys to Bitwarden:")
    print("   • Item name: 'GovInfo API Key'")
    print("   • Item name: 'Congress.gov API Key'")
    print("   • Add custom field 'api_key' with your actual keys")
    print("\n2. Run full setup:")
    print("   python3 scripts/setup_bitwarden.py")
    print("\n3. Set up database:")
    print("   ./scripts/setup_database.sh")
    print("\n4. Start MCP server:")
    print("   npm start")


if __name__ == "__main__":
    main()
